// 9x9 pixel icons over a shared palette. Edit the grids directly; keep each icon
// distinct by silhouette and colour. "." = transparent, other chars = ICON_PALETTE keys.

export const ICON_SIZE = 9;

export const ICON_PALETTE: Record<string, string> = {
  W: '#ffffff',
  w: '#c8d4dc',
  g: '#7a8a96',
  d: '#3c4652',
  k: '#161c24',
  G: '#8ef070',
  v: '#3cb048',
  V: '#1c6a2c',
  C: '#a8f4f4',
  c: '#34bccc',
  t: '#16707c',
  B: '#78b8ff',
  b: '#2e6ad8',
  n: '#1a3688',
  Y: '#fff49a',
  y: '#f4c434',
  o: '#a8741c',
  O: '#ffb048',
  R: '#ff6a3a',
  r: '#c02a1a',
  P: '#ffb4d4',
  p: '#e45096',
  q: '#8e2a5a',
  L: '#dcc0ff',
  l: '#9a66e8',
  m: '#4e2c8c',
  S: '#f2e2c0',
  s: '#c8a470',
  u: '#7c5a38',
  E: '#f4f4ff',
  e: '#b8bce8',
};

export const ICON_DATA = {
  'plankton': [
    '.GG......',
    'GWGv.....',
    'GGvv.GG..',
    '.vv.GWGv.',
    '....GGvv.',
    '.GG..vv..',
    'GWGv.....',
    'GGvv.....',
    '.vv......',
  ],
  'minerite': [
    '....b....',
    '...BWb...',
    '..BBWbb..',
    '.BBBbbbn.',
    '.BBbbbnn.',
    '..Bbbnn..',
    '...bnn...',
    '....n....',
    '.........',
  ],
  'lux': [
    '....y....',
    '.y..y..y.',
    '..yYYYy..',
    '..YWWYy..',
    'yyYWYYyyy',
    '..YYYyo..',
    '..yyyoo..',
    '.y..o..y.',
    '....y....',
  ],
  'nacre': [
    '.........',
    '...eee...',
    '..eWEEe..',
    '.eWEEEEe.',
    '.eEEEEEl.',
    '.eEEEEel.',
    '..eEell..',
    '...lll...',
    '.........',
  ],
  'coral': [
    '.p..p..p.',
    '.P..P..P.',
    '.pP.P.Pp.',
    '..pPPPp..',
    '...pPp...',
    '....P....',
    '...qPq...',
    '..qqqqq..',
    '.........',
  ],
  'shore': [
    '.........',
    '....BBBB.',
    '..BBCCCCB',
    '.BCC...CB',
    '.BC...BB.',
    'BBC..B...',
    'BBBBBBBBb',
    'bbbbbbbbb',
    'nnnnnnnnn',
  ],
  'upgrades': [
    '....c....',
    '...cCc...',
    '..cCCCc..',
    '.cCCCCCc.',
    'cccCCCccc',
    '...cCc...',
    '...cCc...',
    '...ttt...',
    '.........',
  ],
  'achievements': [
    'yYYYYYYYy',
    'y.YYWYy.y',
    'y.YYYYy.y',
    '.yYYYyyy.',
    '..yYyyo..',
    '...yyo...',
    '....o....',
    '...ooo...',
    '..ooooo..',
  ],
  'unique': [
    '.........',
    'y...y...y',
    'yy.yYy.yy',
    'yYyyYyyYy',
    'yYYYYYYYy',
    '.yYYWYYy.',
    '.yyyyyyy.',
    '.ooooooo.',
    '.........',
  ],
  'collection': [
    '..uuuuu..',
    '..sssss..',
    '.wCCCCCw.',
    '.wtPPPtw.',
    '.wtPpPtw.',
    '.wtpPptw.',
    '.wttpttw.',
    '.wwwwwww.',
    '.........',
  ],
  'type-stellarid': [
    '....O....',
    '....O....',
    '...OOO...',
    'OOOOYOOOO',
    '.ROOOOOR.',
    '..ROOOR..',
    '..RO.OR..',
    '.RR...RR.',
    '.R.....R.',
  ],
  'type-blobid': [
    '..LLLLL..',
    '.LLWLLLL.',
    'LLLLLLLLL',
    'lLlLlLlLl',
    '.l.l.l.l.',
    '.l..l..l.',
    '..l..l.l.',
    '.l...l...',
    '.........',
  ],
  'type-corallid': [
    'c...c...c',
    'C..cC..C.',
    '.C.C..C..',
    '.CcC.cC..',
    '..CCcC...',
    '...CC..c.',
    '...CCcC..',
    '...tCt...',
    '..ttttt..',
  ],
  'type-nucleid': [
    '...www...',
    '..wWWWw..',
    '.wW...Ww.',
    'wW.bBb.Ww',
    'wW.BWB.Ww',
    'wW.bBb.Ww',
    '.wg...gw.',
    '..wgggw..',
    '...www...',
  ],
  'type-craboid': [
    'R.......R',
    'RR.....RR',
    '.rR...Rr.',
    '..RRRRR..',
    '.RRWRWRR.',
    'RRRRRRRRR',
    '.rRRRRRr.',
    'r.r...r.r',
    '.........',
  ],
  'ach-shell': [
    '.........',
    '..SSSSS..',
    '.SsSsSsS.',
    'SsSsSsSsS',
    'SsSsSsSsS',
    '.SsSsSsS.',
    '..SsSsS..',
    '...uSu...',
    '..uuuuu..',
  ],
  'up-fertile_waters': [
    '.....GG..',
    '..G.GGv..',
    '.GGvGv...',
    '.GvvG....',
    '...vv....',
    '....v....',
    '....v....',
    '..uuuuu..',
    '.uuuuuuu.',
  ],
  'up-plankton_surge': [
    '.GG...W..',
    'GWGv..W..',
    'GGvvWWWWW',
    '.vv...W..',
    '....GGW..',
    '...GWGv..',
    '...GGvv..',
    '....vv...',
    '.........',
  ],
  'up-magnetic_current': [
    '.........',
    '.rrr.www.',
    'rRRr.wWWw',
    'rR.....Ww',
    'rR.....Ww',
    'rR.....Ww',
    'rRRr.wWWw',
    '.rrr.www.',
    '.........',
  ],
  'up-swift_tides': [
    '.........',
    'B...B....',
    'BB..BB...',
    '.BB..BB..',
    '..BB..BB.',
    '.BB..BB..',
    'BB..BB...',
    'B...B....',
    '.........',
  ],
  'up-bountiful_shore': [
    '.........',
    '.........',
    '....p....',
    '...pPp...',
    '..pPPPp..',
    '...SSS...',
    '.SSSSSSS.',
    'SSSsSSSsS',
    'sssssssss',
  ],
  'up-coral_growth': [
    '.p..p..G.',
    '.P..P.GGG',
    '.pP.PGGGG',
    '..pPPPGG.',
    '...pPpG..',
    '....P....',
    '...qPq...',
    '..qqqqq..',
    '.........',
  ],
  'up-nacre_refinement': [
    '......W..',
    '.....WWW.',
    '...eeeW..',
    '..eWEEe..',
    '.eWEEEEe.',
    '.eEEEEEl.',
    '.eEEEEel.',
    '..eEell..',
    '...lll...',
  ],
  'up-pearl_bloom': [
    '.ggggggg.',
    'gwwwwwwwg',
    '.gwwwwwg.',
    '...eEe...',
    '..eWEEe..',
    '..eEEEl..',
    'gwwlllwwg',
    'gwwwwwwwg',
    '.ggggggg.',
  ],
  'up-rich_brine': [
    '...ggg...',
    '..gdgdg..',
    '..ggggg..',
    '..WWWWw..',
    '..WWWww..',
    '..WWWww..',
    '..WWwww..',
    '..wwwww..',
    '.........',
  ],
  'up-rare_lure': [
    '....ww...',
    '....w....',
    '....w....',
    '....w....',
    '.w..w....',
    '.ww.w..P.',
    '..www.PWP',
    '...w...P.',
    '.........',
  ],
  'up-tide_omen': [
    '.........',
    '..cCCCc..',
    '.c.kkk.c.',
    'c.kyYyk.c',
    '.c.kkk.c.',
    '..cCCCc..',
    '.........',
    'bb.bb.bb.',
    '.bb.bb.bb',
  ],
  'up-deep_drilling': [
    '.gwwwg...',
    'gw...wg..',
    'g...uw...',
    '...u..g..',
    '..u......',
    '.u.......',
    'u........',
    '.........',
    '.........',
  ],
  'up-bioluminescence': [
    '...yyy...',
    '..yYYYy..',
    '.yYWWYYy.',
    '.yYWYYYy.',
    '.yYYYYyo.',
    '..yYYyo..',
    '...ggg...',
    '...ddd...',
    '....d....',
  ],
  'up-mineral_feed': [
    '.........',
    '..b...b..',
    '.BWb.BWb.',
    '.Bbn.Bbn.',
    '..n.b.n..',
    '...BWb...',
    '...Bbn...',
    '...Bbn...',
    '....n....',
  ],
  'up-glow_lure': [
    'u........',
    '.uu......',
    '...uu....',
    '.....u...',
    '......u..',
    '.....yyy.',
    '....yYWYy',
    '.....yYy.',
    '......y..',
  ],
  'mat-stellarid': [
    '.......O.',
    '......OR.',
    '.O...OR..',
    '.RO.OR...',
    '..ROR..O.',
    '...R..OR.',
    '..O..OR..',
    '.OR.OR...',
    '.R..R....',
  ],
  'mat-blobid': [
    '....L....',
    '...LL....',
    '..LLLl...',
    '.LLWLLl..',
    '.LWLLLl..',
    '.LLLLll..',
    '..lLlll..',
    '...lll...',
    '.........',
  ],
  'mat-corallid': [
    '.........',
    '...CCC...',
    '..CWCCc..',
    '.CCCcCcc.',
    '.CcCCccc.',
    '.cCcccct.',
    '..cccctt.',
    '...tttt..',
    '.........',
  ],
  'mat-nucleid': [
    '....w....',
    '...wWw...',
    '..wWWWw..',
    '..wWBWw..',
    '..wWWWg..',
    '..wWWgg..',
    '...wgg...',
    '....g....',
    '.........',
  ],
  'mat-craboid': [
    '.........',
    '..rrrrr..',
    '.rRRRRRr.',
    'rRROROORr',
    'rRRRRRRRr',
    '.r.rRr.r.',
    '....r....',
    '.........',
    '.........',
  ],
  'rare-metallic': [
    '...w.w...',
    '.w.www.w.',
    '..wgggw..',
    'wwg...gww',
    '.wg.d.gw.',
    'wwg...gww',
    '..wgggw..',
    '.w.www.w.',
    '...w.w...',
  ],
  'rare-shiny': [
    '..Y......',
    '..Y......',
    'YYWYY....',
    '..Y...Y..',
    '..Y...Y..',
    '....YYWYY',
    '......Y..',
    '......Y..',
    '.........',
  ],
  'rare-glitch': [
    'GGGGG....',
    'GGGGG....',
    '..GGGGG..',
    '..GGGGG..',
    'pppp.....',
    'pppp.....',
    '...GGGGG.',
    '.GGGGG...',
    '.........',
  ],
  'rare-fire': [
    '....R....',
    '...RR....',
    '...RRR.R.',
    '..RROR.R.',
    '.RROORRR.',
    '.ROOYORR.',
    '.ROYYYOR.',
    '..OYWYO..',
    '...OOO...',
  ],
  'rare-frost': [
    '....C....',
    '.C..C..C.',
    '..C.C.C..',
    '...CWC...',
    'CCCWWWCCC',
    '...CWC...',
    '..C.C.C..',
    '.C..C..C.',
    '....C....',
  ],
  'rare-nebula': [
    '.........',
    '..lll..W.',
    '.lLLLl...',
    'lL...Ll..',
    'lL.W.LL..',
    '.lL...Ll.',
    '..lLLLLl.',
    'W..llll..',
    '.........',
  ],
  'rare-toxic': [
    '....G....',
    '...GG....',
    '...GGv...',
    '..GGWGv..',
    '.GGWGGvv.',
    '.GGGGGvv.',
    '.vGGGvvV.',
    '..vvvvV..',
    '...VVV...',
  ],
  'rare-phantom': [
    '..LLLLL..',
    '.LLLLLLL.',
    'LLkLLkLLL',
    'LLkLLkLLL',
    'LLLLLLLLL',
    'LLLLLLLLL',
    'LLLLLLLLL',
    'L.LL.LL.L',
    '.........',
  ],
  'rare-rotating': [
    '...ccc...',
    '.cc...cc.',
    '.c.....c.',
    'c.....ccc',
    'c......c.',
    'c........',
    '.c.....c.',
    '.cc...cc.',
    '...ccc...',
  ],
  'rare-upside-down': [
    '..O......',
    '.OOO.....',
    'OOOOO....',
    '..O...O..',
    '..O...O..',
    '..O...O..',
    '....OOOOO',
    '.....OOO.',
    '......O..',
  ],
  'rare-wave': [
    '.........',
    '.........',
    '.BB......',
    'B..B...B.',
    '....B.B..',
    '.....B...',
    '.BB......',
    'B..B...B.',
    '....BBB..',
  ],
  'rare-rainbow': [
    '..RRRRR..',
    '.RROOORR.',
    'RROYYYORR',
    'ROYGGGYOR',
    'ROYG.GYOR',
    'OYG...GYO',
    'OYG...GYO',
    '.........',
    '.........',
  ],
  'rare-electric': [
    '.....YY..',
    '....YY...',
    '...YY....',
    '..YYYYY..',
    '....YY...',
    '...YY....',
    '..YY.....',
    '.YY......',
    '.Y.......',
  ],
  'rare-pulse': [
    '.........',
    '.pp...pp.',
    'pPPp.pPPp',
    'pPWPpPPPp',
    'pPPPPPPPp',
    '.pPPPPPp.',
    '..pPPPp..',
    '...pPp...',
    '....p....',
  ],
  'rare-hologram': [
    '....B....',
    '...B.B...',
    '..BBBBB..',
    '.B.....B.',
    'BBBBBBBBB',
    '.B.....B.',
    '..BBBBB..',
    '...B.B...',
    '....B....',
  ],
  'rare-negative': [
    '..WWkkk..',
    '.WWWkkkk.',
    'WWWWkkkkk',
    'WWWWkkkkk',
    'WWWWkkkkk',
    'WWWWkkkkk',
    'WWWWkkkkk',
    '.WWWkkkk.',
    '..WWkkk..',
  ],
  'rare-shadow': [
    '..LLLLL..',
    '.Lmmmmml.',
    'Lmkkkkkml',
    'Lmkkkkkml',
    'Lmkkkkkml',
    'Lmkkkkkml',
    'Lmkkkkkml',
    '.lmmmmml.',
    '..lllll..',
  ],
  'rare-tiny': [
    '.........',
    '.........',
    '.........',
    '...GG....',
    '..GWGv...',
    '..GGvv...',
    '...vv....',
    '.........',
    '.........',
  ],
  'rare-holy': [
    '.YYYYYYY.',
    'Y.......Y',
    '.YYYYYYY.',
    '....W....',
    '..WWWWW..',
    '....W....',
    '....W....',
    '....W....',
    '.........',
  ],
  'rare-xray': [
    '.ww...ww.',
    'wWWw.wWWw',
    '.wWWwWWw.',
    '...wWw...',
    '...wWw...',
    '...wWw...',
    '.wWWwWWw.',
    'wWWw.wWWw',
    '.ww...ww.',
  ],
  'rare-thermal': [
    '....w....',
    '...wRw...',
    '...wRw...',
    '...wRw...',
    '...wRw...',
    '..wRRRw..',
    '..wRORw..',
    '..wRRRw..',
    '...www...',
  ],
  'rare-crt': [
    'ggggggggg',
    'gdddddddg',
    'gdGdGdGdg',
    'gdddddddg',
    'gdGdGdGdg',
    'gdddddddg',
    'ggggggggg',
    '...ggg...',
    '..ddddd..',
  ],
  'rare-caustic': [
    'C..C..C..',
    '.CC.CC.CC',
    '.........',
    '..C..C..C',
    'CC.CC.CC.',
    '.........',
    'C..C..C..',
    '.CC.CC.CC',
    '.........',
  ],
  'rare-stained': [
    '....k....',
    '..kRkBk..',
    '.kRRkBBk.',
    'kkkkkkkkk',
    'kYYkGkPPk',
    'kYYkGkPPk',
    '.kkkkkkk.',
    '..kBBBk..',
    '....k....',
  ],
  'rare-liquify': [
    'BBBBBBBBB',
    'BWBBBBBbB',
    '.BBb.BBb.',
    '.Bb..Bb..',
    '.Bb...b..',
    '..b...B..',
    '..B..Bbb.',
    '.Bbb.bbb.',
    '.bbb.....',
  ],
} as const;

export type IconId = keyof typeof ICON_DATA;
